import Image from 'next/image';
import Link from 'next/link';
import styles from './clientImageSection.module.css';

const getCopyright = (copyright) => {
  if (copyright) {
    return <p className={styles.copyrigth}>Copyright {copyright}</p>;
  }
  return null;
};

export default function ClientImageSection({
  state,
  thumbnails,
  urlNi,
  refNi,
  urlImgproxy,
  title,
  copyright,
  activeDay,
  preset,
}) {
  return (
    <section className={styles.imgSection}>
      <p className={styles.info}>
        Thumbnails are generated by imgproxy on the fly. Each is about 1 KB
        size.
      </p>
      <ul className={styles.list}>
        {thumbnails.map((t) => (
          <li key={t.date}>
            <Link
              className={`${styles.link} ${
                t.date === activeDay ? styles.linkActive : ''
              }`}
              href={`/day/${t.date}?preset=${preset}`}
            >
              <img className={styles.linkImg} src={t.url} alt={t.title} />
            </Link>
          </li>
        ))}
      </ul>
      <div className={styles.imageWrapper}>
        {state === 'imgproxy' && <img src={urlImgproxy} alt={title} />}
        {state === 'nextimage' && (
          <Image
            src={urlNi}
            ref={refNi}
            alt={title}
            layout="fill"
            objectFit="contain"
          />
        )}
        {getCopyright(copyright)}
      </div>
    </section>
  );
}
