'use client';
import ClientSizeSection from './clientSizeSection';
import styles from './clientContentWrap.module.css';

const getCopyright = (copyright) => {
  if (copyright) {
    return <p className={styles.copyrigth}>Copyright {copyright}</p>;
  }
  return null;
};

export default function ClientContentWrap({
  originalSize,
  imgproxySize,
  sizeNI,
  copyright,
  links,
  image,
  children,
}) {
  return (
    <div className={styles.wrapper}>
      <div className={styles.imgSection}>
        <p className={styles.info}>
          Thumbnails are generated by imgproxy on the fly. Each is about 1 KB
          size.
        </p>
        <ul className={styles.list}>{links}</ul>
        <div className={styles.imageWrapper}>
          {image}
          {getCopyright(copyright)}
        </div>
      </div>
      <div className={styles.textWrapper}>
        <ClientSizeSection
          oSize={originalSize}
          iSize={imgproxySize}
          nSize={sizeNI}
        />
        {children}
      </div>
    </div>
  );
}
