import Image from 'next/image';
import styles from './clientImageSection.module.css';

const getCopyright = (copyright) => {
  if (copyright) {
    return <p className={styles.copyrigth}>Copyright {copyright}</p>;
  }
  return null;
};

export default function ClientImageSection({
  state,
  thumbnails,
  urlNi,
  refNi,
  imgproxy,
  copyright,
}) {
  return (
    <section className={styles.imgSection}>
      <p className={styles.info}>
        Thumbnails are generated by imgproxy on the fly. Each is about 1 KB
        size.
      </p>
      <ul className={styles.list}>{thumbnails}</ul>
      <div className={styles.imageWrapper}>
        {state === 'imgproxy' && imgproxy}
        {state === 'nextimage' && (
          <Image
            src={urlNi}
            ref={refNi}
            layout="fill"
            objectFit="contain"
            alt="Image of the day"
          />
        )}
        {getCopyright(copyright)}
      </div>
    </section>
  );
}
